name: Update M3U with Token

on:
  schedule:
    - cron: '0 * * * *'  # প্রতি ঘণ্টায় চালাবে
  workflow_dispatch:      # ম্যানুয়ালি চালানো যাবে

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run update script
        env:
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
        run: python update_m3u.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add ottrxs.m3u
          git commit -m "Auto-update M3U with token" || echo "No changes"
          git push
